export enum CodeChatActions {
  RESET_CODE_CHAT_STORE = "RESET_CODE_CHAT_STORE",
  UPDATE_CURRENT_PATH = "UPDATE_CURRENT_PATH",
  UPDATE_SELECTED_FILES = "UPDATE_SELECTED_FILES",
  UPDATE_RECENT_FILES = "UPDATE_RECENT_FILES",
  UPDATE_SELECTED_AGENT = "UPDATE_SELECTED_AGENT",
  UPDATE_CHAT_HISTORY = "UPDATE_CHAT_HISTORY",
  UPDATE_CHAT_IS_LOADING = "UPDATE_CHAT_IS_LOADING",
  UPDATE_COLLAPSED_STATE = "UPDATE_COLLAPSED_STATE",
  UPDATE_FILE_CONTENT_POPUP = "UPDATE_FILE_CONTENT_POPUP",
  UPDATE_TOKEN_COUNT = "UPDATE_TOKEN_COUNT",
}
