export enum CodeChatActions {
  RESET_CODE_CHAT_STORE = "RESET_CODE_CHAT_STORE",
  UPDATE_CURRENT_PATH = "UPDATE_CURRENT_PATH",
  UPDATE_SELECTED_FILES = "UPDATE_SELECTED_FILES",
  UPDATE_RECENT_FILES = "UPDATE_RECENT_FILES",
  UPDATE_SELECTED_AGENT = "UPDATE_SELECTED_AGENT",
  CLEAR_CHATS = "CLEAR_CHATS",
  UPDATE_CHAT_HISTORY = "UPDATE_CHAT_HISTORY",
  UPDATE_CHAT_IS_LOADING = "UPDATE_CHAT_IS_LOADING",
  UPDATE_FILE_CONTENT_POPUP = "UPDATE_FILE_CONTENT_POPUP",
  UPDATE_TOKEN_COUNT = "UPDATE_TOKEN_COUNT",
  UPDATE_SAVED_PLANS = "UPDATE_SAVED_PLANS",
  UPDATE_SAVED_CHATS = "UPDATE_SAVED_CHATS",
  UPDATE_STAGE = "UPDATE_STAGE",
  UPDATE_BREADCRUMB = "UPDATE_BREADCRUMB",
  UPDATE_OPEN_MODALS = "UPDATE_OPEN_MODALS",
  UPDATE_COLLAPSED_SECTIONS = "UPDATE_COLLAPSED_SECTIONS",
  UPDATE_FILE_TREE_DATA = "UPDATE_FILE_TREE_DATA" // New action
}

