export enum ResearchActions {
    UPDATE_QUERY = 'UPDATE_QUERY',
    SET_LOADING = 'SET_LOADING',
    SET_ERROR = 'SET_ERROR',
    SET_RESULTS = 'SET_RESULTS',
    ADD_TO_HISTORY = 'ADD_TO_HISTORY',
    CLEAR_RESULTS = 'CLEAR_RESULTS',
    RESET_STORE = 'RESET_STORE',
}
