name: Cypress Tests

on:
  push:
    branches:
      - '*' # Run on all branches
  pull_request:
    branches:
      - '*' # Run on all branches

jobs:
  run-cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Replace with the Node.js version used in your project
      - name: Install dependencies
        run: npm install

      - name: Run Cypress e2e tests
        run: npm run cy:e2e

  run-cypress-component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Replace with the Node.js version used in your project
      - name: Install dependencies
        run: npm install
      - name: Run Cypress component tests
        run: npm run cy:component
